{% set version = "0.7.2" %}

package:
  name: genshi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/Genshi/Genshi-{{ version }}.tar.gz
  sha256: 7e90bd5d8d5b3d6bef9af6abacf271faca00f0f9512642d75e0e02cb79f7ba9f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - genshi
    - genshi.filters
    - genshi.filters.tests
    - genshi.template
    - genshi.template.tests
    - genshi.template.tests.templates
    - genshi.tests

about:
  home: http://genshi.edgewall.org/
  license: BSD-3-Clause
  license_file: COPYING
  summary: A toolkit for generation of output for the web

extra:
  recipe-maintainers:
    - ocefpaf
