{% set version = "0.7.4" %}

package:
  name: genshi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/Genshi/Genshi-{{ version }}.tar.gz
  sha256: d92ef3bb34474a38566f7e44e570ff3067c7f7c126670c79f660661badf8eddb

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - genshi
    - genshi.filters
    - genshi.template
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://genshi.edgewall.org/
  summary: A toolkit for generation of output for the web
  doc_url: https://pythonhosted.org/Genshi/
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - ocefpaf
