{% set version = "0.7.1" %}

package:
  name: genshi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/Genshi/Genshi-{{ version }}.tar.gz
  sha256: 0d87ae62cf2ed92133f35725da51e02d09f79bb4cb986f0d948408a0279dd3f8

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - genshi
    - genshi.filters
    - genshi.filters.tests
    - genshi.template
    - genshi.template.tests
    - genshi.template.tests.templates
    - genshi.tests

about:
  home: http://genshi.edgewall.org/
  license: BSD-3-Clause
  license_file: COPYING
  summary: A toolkit for generation of output for the web

extra:
  recipe-maintainers:
    - ocefpaf
