{% set version = "0.7" %}

package:
  name: genshi
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/G/Genshi/Genshi-{{ version }}.tar.gz
  sha256: 

build:
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - genshi
    - genshi.filters
    - genshi.filters.tests
    - genshi.template
    - genshi.template.tests
    - genshi.template.tests.templates
    - genshi.tests

about:
  home: http://genshi.edgewall.org/
  license: BSD-3-Clause
  summary: A toolkit for generation of output for the web

extra:
  recipe-maintainers:
    - ocefpaf
