appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DwcYAyssUnqsHzRQ1UmXCNW7rbI/7lIdqz5zntDP+zn0nOZfQjj7YurzQEPOxwPGTN+xPkdTA5y0Upn//BGyhP63s0hUBfTceE9FL+D9sDu485/nGkoDlKcGdqV6x93g2aQeiCoHamvjAqBHAd/25p/QadXfQVjadr56SN1UZXQxBRbOvHtkCPd2Nv3Q8fPCVhcBZSPNypXHSmtVhEzah23QFpTO4tsIcZeeuXwEbqtnlIlvvykzeFwC5gzFQxcY2dXjCjMIeoNTnCItVo1GvBAIRs2MkvRNbmIxAYI9kqRKqsYZVmCpePApkRH18+ZNWqh1I/exxwPpixWRd7OUUCLidRNUgm6xd8Wlh7gRRDITXFGiUBnhGNX2nPW0YbAeDSGV47Sno5M7Bi8hroaz2gV5OdE5mkJWqSTDOgbfQ8ZBLJdOzZUUbMLXk0WM/FWUhq1ablEB0/JgoVdlnQ0EuIueO616fkfug2H6JB8MAwZdkDLiUt373uKadkj5zvmr+LjYHNeulgLZ1IH5l7QH4Gl1wyX/u7l/OhsLrXX+qT1hAUcPkF4VBbKHyqxKswrUkwCvGYbJwWrDub4ID1WKGAwGthsoFS3UCz4sPscrKTOM8+RLe0gtnQWevlyBrqDKh6FZl28WboO9CYPal752oHHYulmY0RthckOC0ytd6QU=}
