travis:
  secure:
    BINSTAR_TOKEN: pUVRSQYKPkdv6hARAv7pApADUma05AO433V7vTltm0/ptbRCGT+YT5DjyFD9t5Nyl3Ab+zP97bpTaX/Jcht5x/yM61BkfLyGJvIA7REbHmGtCA+67n2gxP6eWJZkaQ7LLyjh36J/6eHghCaGyp1JvK1thoruz3ujO9osP8j/I+K0Z9yIRt3suZ3y3KElKD3Aqz+b4N2TjX7ZDSbgamw1yRd7KjqFuLeup/0nqUf7m19CR8ln3KrSXSgtsFyHMRV20wkhx0MbFgRJZEHgOeq4ddy0l/CiXu7tLl4FlqcVB3kBSJYMKZrlUgbyX/u0BT3PTTvLADEeFc6LU9h+pekGeGIPa8T6XLlfuFuVA+Khb5XQ7WT20ru4oaELEPHQev48yStMejdI8sRZ6kzvwngdEsr9Qbho5ugujtEicxitpqxqImAzC1sHUKo2GGe52kJxiZpbCKfgym+/yFIwho4Gwf+6PN7m5b01YwCsC4gQZIwK/5qgz7qxe9tM+DgctSe4k2v+x8XuNlCs76rzEW4huFS7h4ZqBFDvknwMyPpY0RGfKGtNlTYzjLOa9loc82dDK7qZ2psdzeXKNBm0Hniauy1Ut/klNbFXYz1Yko4YtWA0pXo5oBCHMgQ7c7kZxQIfJWaDrnUk/wEFgPzGrKMyymPej0dlDnMBhWcj7f8ueL8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
